---
- name: Check deployment
  ansible.builtin.import_playbook: playbooks/check_deployment.yml
- name: Import Prepare playbook
  import_playbook: playbooks/prepare.yml
  when: deployment | lower == "greenfield"
- name: Import Backup playbook
  import_playbook: playbooks/backup.yml
  when: deployment | lower == "brownfield"
- name: Import MariaDB playbook
  import_playbook: playbooks/mariadb.yml
  when: _mariadb == 1
- name: Import Passbolt playbook
  import_playbook: playbooks/passbolt.yml
  when: _passbolt == 1
- name: Import Restore playbook
  import_playbook: playbooks/restore.yml
  when: deployment | lower == "greenfield"
