---
- name: Import restore_mariadb task
  ansible.builtin.import_tasks: restore_mariadb.yml
  when: _mariadb == 1 and inventory_hostname in groups['mariadb']
- name: Import restore_passbolt task
  ansible.builtin.import_tasks: restore_passbolt.yml
  when: _passbolt == 1 and inventory_hostname in groups['passbolt']
