---
- name: download passbolt backups from Azure
  ansible.builtin.command: "az storage blob download
    --account-name {{ account }} --container {{ container }} --name {{ item | basename }}.zip --file {{ item | basename }}.zip --account-key {{ key }}"
  with_items:
    - "{{ _mariadb_backup }}"
  when: _restore_from_backup.azure == 1
- name: download passbolt backups from AWS
  amazon.aws.aws_s3:
    aws_access_key: "{{ _aws_access_key }}"
    aws_secret_key: "{{ _aws_secret_key }}"
    mode: get
    bucket: "{{ _aws_bucket }}"
    object: "passbolt/{{ item | basename }}.zip"
    dest: "$HOME/{{ item | basename }}.zip"
  with_items:
    - "{{ _mariadb_backup }}"
  when: _restore_from_backup.aws == 1
- name: download passbolt backups from Linode
  ansible.builtin.command: "s3cmd get
    --access_key={{ _linode_access_key }} --secret_key={{ _linode_secret_key }}
    --host={{ _host }} --no-ssl --host-bucket={{ _host }} s3://{{ _linode_bucket }}/passbolt/{{ item | basename }}.zip"
  with_items:
    - "{{ _mariadb_backup }}"
  when: _restore_from_backup.linode == 1
- name: unzip mariadb backup
  become: true
  ansible.builtin.unarchive:
    src: $HOME/{{ item | basename }}.zip
    dest: /
    remote_src: true
    extra_opts:
      - "P"
      - "{{ _zip_password }}"
  with_items:
    - "{{ _mariadb_backup }}"
- name: import mariadb sql backup
  become: true
  community.docker.docker_container_exec:
    container: "{{ _mariadb_name }}"
    command: /bin/sh -c "mysql -u{{ _mariadb_username }} -p{{ _mariadb_password }} {{ _mariadb_database }} < /var/lib/mysql/passbolt.sql"
- name: remove backups from the host
  ansible.builtin.file:
    state: absent
    path: "{{ item }}.zip"
  with_items:
    - "{{ _mariadb_backup }}"
