---
- name: Download mariadb backups from Azure
  ansible.builtin.command: >
    az storage blob download
    --account-name {{ restore_from_backup_account }}
    --container {{ restore_from_backup_container }}
    --name {{ item | basename }}.zip
    --file {{ item | basename }}.zip
    --account-key {{ restore_from_backup_key }}
  with_items:
    - "{{ restore_from_backup_mariadb_backup }}"
  when: _restore_from_backup.azure == 1
  changed_when: false

- name: Download mariadb backups from AWS
  amazon.aws.aws_s3:
    aws_access_key: "{{ _aws_access_key }}"
    aws_secret_key: "{{ _aws_secret_key }}"
    mode: get
    bucket: "{{ _aws_bucket }}"
    object: "mariadb/{{ item | basename }}.zip"
    dest: "$HOME/{{ item | basename }}.zip"
  with_items:
    - "{{ restore_from_backup_mariadb_backup }}"
  when: _restore_from_backup.aws == 1

- name: Download mariadb backups from Linode
  ansible.builtin.command: >
    s3cmd get
    --access_key={{ _linode_access_key }}
    --secret_key={{ _linode_secret_key }}
    --host={{ _host }}
    --no-ssl --host-bucket={{ _host }}
    s3://{{ _linode_bucket }}/mariadb/{{ item | basename }}.zip
  with_items:
    - "{{ restore_from_backup_mariadb_backup }}"
  when: _restore_from_backup.linode == 1
  changed_when: false

- name: Unzip mariadb backup
  become: true
  ansible.builtin.unarchive:
    src: "$HOME/{{ item | basename }}.zip"
    dest: /
    remote_src: true
    extra_opts:
      - "P"
      - "{{ _zip_password }}"
  with_items:
    - "{{ restore_from_backup_mariadb_backup }}"

- name: Import mariadb sql backup
  become: true
  community.docker.docker_container_exec:
    container: "{{ _mariadb_name }}"
    command: /bin/sh -c "mysql -u{{ _mariadb_username }} -p{{ _mariadb_password }} {{ _mariadb_database }} < /var/lib/mysql/passbolt.sql"
  with_items:
    - "{{ restore_from_backup_mariadb_backup }}"

- name: Remove mariadb backups from the host
  ansible.builtin.file:
    state: absent
    path: "$HOME/{{ item | basename }}.zip"
  with_items:
    - "{{ restore_from_backup_mariadb_backup }}"
