---
- name: install all necessary packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ _debian_packages }}"
    - "{{ _python_packages }}"
- name: add docker gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
- name: add docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename | lower }} stable'
    state: present
    update_cache: true
- name: install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ _docker_packages }}"
- name: enable docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted
- name: install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/{{ _docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+x'
- name: install required python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
  loop: "{{ _python_pip_packages }}"
