FROM moleszek/ansible:13.2.0

ARG username=vscode

ENV USER=${username}
ENV USERNAME=${username}
ENV PATH="/home/${username}/.local/bin:${PATH}"

RUN apt update && apt upgrade -y && apt install curl git -y && apt autoremove -y && apt clean\
  && useradd -ms /bin/bash ${username} \
  && pip install pre-commit --break-system-packages \
  && curl -o /tmp/install.sh https://starship.rs/install.sh \
  && sh /tmp/install.sh -y \
  && mkdir /home/${username}/.config \
  && starship preset no-empty-icons -o /home/${username}/.config/starship.toml \
  && echo 'eval "$(starship init bash)"' >> /home/${username}/.bashrc

WORKDIR /home/${username}

ENTRYPOINT [ "bash" ]
