---
- name: Remove MariaDB container
  ansible.builtin.docker_container:
    name: "{{ _mariadb_name }}"
    state: absent
- name: Remove old MariaDB docker image
  ansible.builtin.docker_container:
    state: absent
    name: mariadb
    tag: "{{ _mariadb_restore_version }}"
