---
- name: Remove MariaDB container
  community.docker.docker_container:
    name: "{{ _mariadb_name }}"
    state: absent
- name: Remove old MariaDB docker image
  community.docker.docker_image:
    state: absent
    name: mariadb
    tag: "{{ _mariadb_restore_version }}"
