---
- name: pull MariaDB docker image
  docker_image:
    name: "mariadb:{{ _mariadb_version }}"
- name: create docker network
  docker_network:
    name: "{{ _mariadb_net }}"
    state: present
  when: aio == 0
- name: create mariadb folder
  ansible.builtin.file:
    path: "{{ _mariadb_folder }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
- name: create mariadb docker volume
  docker_volume:
    name: mariadb-data
    driver_options:
      type: none
      device: /var/mariadb
      o: bind
