---
- name: Pull MariaDB docker image
  community.docker.docker_image:
    name: "mariadb:{{ _mariadb_version }}"
    source: pull
- name: Create docker network
  community.docker.docker_network:
    name: "{{ _mariadb_net }}"
    state: present
  when: aio == 0
- name: Create mariadb folder
  ansible.builtin.file:
    path: "{{ mariadb_folder }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
- name: Create mariadb docker volume
  community.docker.docker_volume:
    name: mariadb-data
    driver_options:
      type: none
      device: /var/mariadb
      o: bind
