---
- name: Import greenfield task
  ansible.builtin.import_tasks: greenfield.yml
  when: deployment == "greenfield"
- name: Import brownfield task
  ansible.builtin.import_tasks: brownfield.yml
  when: deployment == "brownfield"
- name: Import MariaDB task
  ansible.builtin.import_tasks: mariadb.yml
