---
- name: "{{ _task_name }}"
  ansible.builtin.docker_container:
    name: "{{ _mariadb_name }}"
    image: "mariadb:{{ _version }}"
    state: started
    network_mode: "{{ _check_aio }}"
    networks:
      - name: "{{ _check_aio }}"
    ports:
      - "{{ _mariadb_port }}:3306/tcp"
    volumes:
      - mariadb-data:/var/lib/mysql
    env:
      TZ: "{{ _time_zone }}"
      MYSQL_ROOT_PASSWORD: "{{ _mariadb_root_password }}"
      MYSQL_PASSWORD: "{{ _mariadb_password }}"
      MYSQL_USER: "{{ _mariadb_username }}"
      MYSQL_DATABASE: "{{ _mariadb_database }}"
    hostname: "{{ _mariadb_name }}"
    restart_policy: unless-stopped
