---
_debian_packages: [apt-transport-https, ca-certificates, curl, software-properties-common, gnupg-agent, ufw, zip, unzip, s3cmd]
_docker_packages: [docker-ce, docker-ce-cli, containerd.io]
_python_packages: [python3, python3-pip]
_python_pip_packages: [docker, docker-compose, boto3]
