---
backup_acc: "{{ _account_name }}"
backup_cont: "{{ _container_name }}"
backup_key: "{{ _account_key }}"
backup_passbolt_backup: [/var/passbolt/gpg, /var/passbolt/jwt]
backup_mariadb_backup: [/var/mariadb]
