---
_passbolt_folder: [/var/passbolt/gpg, /var/passbolt/certs, /var/passbolt/jwt]
_mariadb_ip_address: "{%- for host in groups['mariadb'] -%} {{ hostvars[host]['groups']['mariadb'][0] }} {%- endfor %}"
