---
- hosts: mariadb
  become: true
  gather_facts: true
  name: MariaDB
  tasks:
    - name: Restore MariaDB on fail
      block:
        - name: Install MariaDB
          vars:
            mariadb_version: "{{ _mariadb_version }}"
            mariadb_task_name: "run MariaDB in version: {{ _mariadb_version }}"
          ansible.builtin.import_role:
            name: mariadb
      rescue:
        - name: Set MariaDB restore variables
          ansible.builtin.set_fact:
            mariadb_version: "{{ _mariadb_restore_version }}"
            mariadb_task_name: "restore MariaDB to version: {{ _mariadb_restore_version }}"
          when: deployment | lower == "brownfield"
        - name: Include MariaDB restore role
          ansible.builtin.include_role:
            name: mariadb
          when: deployment | lower == "brownfield"
