---
- hosts: passbolt
  become: true
  gather_facts: true
  name: Passbolt
  tasks:
    - name: Restore Passbolt if installation failed
      block:
        - name: Install Passbolt
          vars:
            passbolt_version: "{{ _passbolt_version }}"
            passbolt_task_name: "run Passbolt in version: {{ _passbolt_version }}"
          ansible.builtin.import_role:
            name: passbolt
      rescue:
        - name: Set Passbolt restore variables
          ansible.builtin.set_fact:
            passbolt_version: "{{ _passbolt_restore_version }}"
            passbolt_task_name: "restore Passbolt to version: {{ _passbolt_restore_version }}"
          when: deployment | lower == "brownfield"
        - name: Include Passbolt restore role
          ansible.builtin.include_role:
            name: passbolt
          when: deployment | lower == "brownfield"
