---
- hosts: passbolt
  become: true
  gather_facts: true
  name: Passbolt
  tasks:
    - name: Restore on failure
      block:
        - name: Install Passbolt
          vars:
            _version: "{{ _passbolt_version }}"
            _task_name: "run Passbolt in version: {{ _passbolt_version }}"
          ansible.builtin.import_role:
            name: ../roles/passbolt
      rescue:
        - name: Do not restore in greenfield
          ansible.builtin.fail:
            msg: "Installation failed!"
          when: deployment | lower == "greenfield"
        - name: Restore Passbolt on fail
          vars:
            _version: "{{ _passbolt_restore_version }}"
            _task_name: "restore Passbolt to version: {{ _passbolt_restore_version }}"
          ansible.builtin.include_role:
            name: ../roles/passbolt/tasks/passbolt.yml
          when: deployment | lower == "brownfield"
