---
- hosts: passbolt
  become: true
  name: Prepare
  roles:
    - role: ../roles/prepare
      when: aio == 1

- hosts: mariadb, passbolt
  name: Prepare
  become: true
  roles:
    - role: ../roles/prepare
      when: aio != 1
