name: Ansible Lint
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"
jobs:
  ansible-lint:
    name: Run Ansible lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check yaml files
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          playbooks/*.yml
          roles/backup/tasks/*.yml
          roles/backup/vars/*.yml
          roles/mariadb/tasks/*.yml
          roles/mariadb/vars/*.yml
          roles/passbolt/tasks/*.yml
          roles/passbolt/vars/*.yml
          roles/prepare/tasks/*.yml
          roles/prepare/vars/*.yml
          roles/restore_from_backup/tasks/*.yml
          roles/restore_from_backup/vars/*.yml
        args: -v -x 303
