---
- name: remove Passbolt container
  docker_container:
    name: "{{ _passbolt_name }}"
    state: absent
- name: remove old Passbolt docker image
  docker_image:
    state: absent
    name: passbolt/passbolt
    tag: "{{ _passbolt_restore_version }}"
