---
- name: Pull Passbolt docker image
  community.docker.docker_image:
    name: "passbolt/passbolt:{{ _passbolt_version }}"
    source: pull
- name: Create docker network
  community.docker.docker_network:
    name: "{{ _passbolt_net }}"
    state: present
  when: aio == 0
- name: Create passbolt folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0440"
  loop: "{{ passbolt_folder }}"
- name: Create passbolt gpg docker volume
  community.docker.docker_volume:
    name: "passbolt-{{ item | basename }}"
    driver_options:
      type: none
      device: "{{ item }}"
      o: bind
  with_items:
    - "{{ passbolt_folder }}"
