---
- name: Pull Passbolt docker image
  ansible.builtin.docker_image:
    name: "passbolt/passbolt:{{ _passbolt_version }}"
- name: Create docker network
  ansible.builtin.docker_network:
    name: "{{ _passbolt_net }}"
    state: present
  when: aio == 0
- name: Create passbolt folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0440
  loop: "{{ _passbolt_folder }}"
- name: Create passbolt gpg docker volume
  ansible.builtin.docker_volume:
    name: "passbolt-{{ item | basename }}"
    driver_options:
      type: none
      device: "{{ item }}"
      o: bind
  with_items:
    - "{{ _passbolt_folder }}"
